// Code generated by Slice Machine. DO NOT EDIT.

import Button from './Button';
import ContactForm from './ContactForm';
import Image from './Image';
import Quote from './Quote';
import Text from './Text';

export {
	Button,
	ContactForm,
	Image,
	Quote,
	Text,
};

export const components = {
	button: Button,
	contact_form: ContactForm,
	image: Image,
	quote: Quote,
	text: Text,
};
